Task 1
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

In [ ]:
def convert_units(value, conversion_factor):
    """Convert units using a given conversion factor."""
    return value * conversion_factor

def main():
    print("Unit Converter")
    print("1. Meters to Feet\n2. Feet to Meters\n3. Kilograms to Pounds")
    print("4. Pounds to Kilograms\n5. Liters to Gallons\n6. Gallons to Liters")

    choice = input("Enter your choice (1-6): ")
    conversions = {
        "1": ("Meters", "Feet", 3.28084),
        "2": ("Feet", "Meters", 1 / 3.28084),
        "3": ("Kilograms", "Pounds", 2.20462),
        "4": ("Pounds", "Kilograms", 1 / 2.20462),
        "5": ("Liters", "Gallons", 0.264172),
        "6": ("Gallons", "Liters", 1 / 0.264172),
    }

    if choice in conversions:
        unit_from, unit_to, factor = conversions[choice]
        try:
            value = float(input(f"Enter value in {unit_from}: "))
            result = convert_units(value, factor)
            print(f"{value} {unit_from} = {result:.4f} {unit_to}")
        except ValueError:
            print("Invalid input! Please enter a number.")
    else:
        print("Invalid choice! Please select a valid option.")

if __name__ == "__main__":
    main()


Unit Converter
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter your choice (1-6): a
Invalid choice! Please select a valid option.


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

In [ ]:
def calculate_sum(numbers):
    """Returns the sum of the given list of numbers."""
    return sum(numbers)

def calculate_average(numbers):
    """Returns the average of the given list of numbers."""
    return sum(numbers) / len(numbers) if numbers else 0  # Avoid division by zero

def find_maximum(numbers):
    """Returns the maximum value from the given list of numbers."""
    return max(numbers)

def find_minimum(numbers):
    """Returns the minimum value from the given list of numbers."""
    return min(numbers)

def main():
    print("Math Operations on a List")
    print("1. Sum\n2. Average\n3. Maximum\n4. Minimum")

    choice = input("Enter your choice (1-4): ")
    if choice not in ["1", "2", "3", "4"]:
        print("Invalid choice! Please select a valid option.")
        return

    try:
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))
        if not numbers:
            raise ValueError("The list is empty. Please enter at least one number.")
    except ValueError as e:
        print("Invalid input!", e)
        return

    operations = {
        "1": ("Sum", calculate_sum),
        "2": ("Average", calculate_average),
        "3": ("Maximum", find_maximum),
        "4": ("Minimum", find_minimum),
    }

    operation_name, operation_func = operations[choice]
    result = operation_func(numbers)

    print(f"{operation_name}: {result}")

if __name__ == "__main__":
    main()


Math Operations on a List
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 4
Enter numbers separated by spaces: 10 20 30 5
Minimum: 5.0


Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    return lst[::2]
numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)
print(result)


[1, 3, 5]


Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
def get_sublist(lst,start,end):
  return lst[start:end+1]
numbers=[1,2,3,4,5,6]
sublist=get_sublist(numbers,2,4)
print(sublist)

[3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
  return lst[::-1]

numbers=[5,4,3,2,1]
reversed_list=reverse_list(numbers)
print(reversed_list)

[1, 2, 3, 4, 5]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
  return lst[1:-1]
numbers=[1,2,3,4,5]
result=remove_first_last(numbers)
print(result)

[2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst,n):
  return lst[:n]
numbers=[1,2,3,4,5]
result=get_first_n(numbers,3)
print(result)

[1, 2, 3]


Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst,n):
  return lst[-n:   ]
numbers=[1,2,3,4,5]
result=get_last_n(numbers,2)
print(result)


[4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
    return lst[-2::-2]  # Slicing from second-to-last element and skipping one element backward

numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)
print(result)


[5, 3, 1]


Exercise on Nested List:
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
    return [item for sublist in lst for item in sublist]


nested_list = [[1, 2], [3, 4], [5]]
result = flatten(nested_list)
print(result)


[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]
    return lst


nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)
print(result)

6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    total = 0
    for element in lst:
        if isinstance(element, list):
            total += sum_nested(element)
        else:
            total += element
    return total


nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print(result)


21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            filtered_sublist = remove_element(item, elem)  # Recursively process sublists
            if filtered_sublist:  # Only add non-empty sublists
                result.append(filtered_sublist)
        elif item != elem:  # Keep the item if it's not the target element
            result.append(item)
    return result


nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2
result = remove_element(nested_list, element_to_remove)
print(result)


[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    max_value = float('-inf')  # Initialize max_value to negative infinity

    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))  # Recursively find max in sublists
        else:
            max_value = max(max_value, item)  # Compare with current max

    return max_value


nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print(result)


6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:
def count_occurrences(lst, elem):
    count = 0  # Initialize count

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # Recursively count in sublists
        elif item == elem:
            count += 1  # Increment count if the element matches

    return count


nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(nested_list, element_to_count)
print(result)


3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    flattened = []  # Initialize an empty list to store the flattened elements

    for item in lst:
        if isinstance(item, list):
            flattened.extend(deep_flatten(item))  # Recursively flatten sublists
        else:
            flattened.append(item)  # Add non-list items directly to the flattened list

    return flattened
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    def deep_flatten(lst):
        flattened = []
        for item in lst:
            if isinstance(item, list):
                flattened.extend(deep_flatten(item))  # Recursively flatten sublists
            else:
                flattened.append(item)
        return flattened

    flattened_list = deep_flatten(lst)  # Get a single-level list
    if not flattened_list:  # Handle empty lists
        return 0

    return sum(flattened_list) / len(flattened_list)  # Calculate the average


nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print(result)

3.5


10. To - Do - NumPy
10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np


empty_array = np.empty((2, 2))
print("Empty 2x2 Array:\n", empty_array)

ones_array = np.ones((4, 2))
print("\nAll Ones 4x2 Array:\n", ones_array)


fill_value_array = np.full((3, 3), 7)  # Example: A 3x3 array filled with 7
print("\n3x3 Array Filled with 7:\n", fill_value_array)


reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(reference_array)
print("\nZeros Array with Same Shape as Reference Array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\nOnes Array with Same Shape as Reference Array:\n", ones_like_array)

# 6. Convert a list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:\n", numpy_array)


Empty 2x2 Array:
 [[2.12963247e-316 0.00000000e+000]
 [7.35874515e+223 6.52022889e+252]]

All Ones 4x2 Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3x3 Array Filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array with Same Shape as Reference Array:
 [[0 0 0]
 [0 0 0]]

Ones Array with Same Shape as Reference Array:
 [[1 1 1]
 [1 1 1]]

Converted NumPy Array:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_10_49 = np.arange(10, 50)
print("Array from 10 to 49:\n", array_10_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array_30 = np.random.random(30)
mean_value = random_array_30.mean()
print("\nRandom array of size 30:\n", random_array_30)
print("Mean of the array:", mean_value)

# 5. Create a 10x10 array with random values and find the min and max values
random_matrix_10x10 = np.random.random((10, 10))
min_value = random_matrix_10x10.min()
max_value = random_matrix_10x10.max()
print("\n10x10 Random Matrix:\n", random_matrix_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Index 4 is the 5th element (0-based indexing)
print("\nZero Array with 5th Element as 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with Border 1 and Inside 0:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Fill 1 in alternate positions
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
 [0.8910879  0.61621692 0.56496837 0.46448959 0.32651584 0.26209829
 0.06910168 0.84295384 0.55217501 0.33475308 0.79212266 0.02622532
 0.47679907 0.38591462 0.73270767 0.0604923  0.72140644 0.35547536
 0.26743839 0.8550456  0.70010356 0.43326857 0.97340012 0.22312646
 0.87680207 0.90716324 0.63224768 0.19632197 0.9927671  0.215425  ]
Mean of the array: 0.524953790662278

10x10 Random Matrix:
 [[0.72965699 0.7611198  0.89570194 0.35833247 0.84482467 0.63529551
  0.96324628 0.20331422 0.87637961 0.65165281]
 [0.66533934 0.83570853 0.30616946 0.86458276 0.90828235 0.11738779
  0.23124544 0.17445921 0.43212224 0.67475678]
 [0.48537172 0.52658854 0.76255328 0.36684898 0.5023933  0.83328725
  0.2496

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

# Define the given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays (element-wise)
add_xy = x + y
print("Addition of x and y:\n", add_xy)

# 2. Subtract the two arrays (element-wise)
subtract_xy = x - y
print("\nSubtraction of x and y:\n", subtract_xy)

# 3. Multiply the array x with an integer (e.g., 3)
multiply_x = x * 3
print("\nMultiplication of x with 3:\n", multiply_x)

# 4. Find the square of each element of x
square_x = np.square(x)
print("\nSquare of each element in x:\n", square_x)

# 5. Find the dot product
dot_vw = np.dot(v, w)  # Dot product of vectors v and w
dot_xv = np.dot(x, v)  # Dot product of matrix x and vector v
dot_xy = np.dot(x, y)  # Dot product of matrices x and y

print("\nDot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

# 6. Concatenate x and y along rows (axis=0)
concat_xy = np.concatenate((x, y), axis=0)
print("\nConcatenation of x and y along rows:\n", concat_xy)

# Concatenate v and w along columns (reshaping them to column vectors)
concat_vw = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("\nConcatenation of v and w along columns:\n", concat_vw)

# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)  # Attempting to concatenate x and v
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError while concatenating x and v:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]

Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


10.2 Experiment: How Fast is Numpy?

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import time
import numpy as np

# Create two lists of size 1,000,000 with random values
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000000, 0, -1)]

# Measure time for Python List element-wise addition
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()
print(f"Time taken for element-wise addition using Python Lists: {end_time - start_time} seconds")

# Create two numpy arrays of size 1,000,000 with random values
array1 = np.arange(1, 1000001)
array2 = np.arange(1000000, 0, -1)

# Measure time for Numpy Array element-wise addition
start_time = time.time()
result_array = array1 + array2
end_time = time.time()
print(f"Time taken for element-wise addition using Numpy Arrays: {end_time - start_time} seconds")


Time taken for element-wise addition using Python Lists: 0.1358168125152588 seconds
Time taken for element-wise addition using Numpy Arrays: 0.013085365295410156 seconds


2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import time
import numpy as np

# Create two lists of size 1,000,000 with random values
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000000, 0, -1)]

# Measure time for Python List element-wise multiplication
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(len(list1))]
end_time = time.time()
print(f"Time taken for element-wise multiplication using Python Lists: {end_time - start_time} seconds")

# Create two numpy arrays of size 1,000,000 with random values
array1 = np.arange(1, 1000001)
array2 = np.arange(1000000, 0, -1)

# Measure time for Numpy Array element-wise multiplication
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
print(f"Time taken for element-wise multiplication using Numpy Arrays: {end_time - start_time} seconds")


Time taken for element-wise multiplication using Python Lists: 0.09694623947143555 seconds
Time taken for element-wise multiplication using Numpy Arrays: 0.007936477661132812 seconds


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import time
import numpy as np

# Create two lists of size 1,000,000 with random values
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000000, 0, -1)]

# Measure time for Python List dot product
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end_time = time.time()
print(f"Time taken for dot product using Python Lists: {end_time - start_time} seconds")

# Create two numpy arrays of size 1,000,000 with random values
array1 = np.arange(1, 1000001)
array2 = np.arange(1000000, 0, -1)

# Measure time for Numpy Array dot product
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
print(f"Time taken for dot product using Numpy Arrays: {end_time - start_time} seconds")


Time taken for dot product using Python Lists: 0.12972736358642578 seconds
Time taken for dot product using Numpy Arrays: 0.0023522377014160156 seconds


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
import time
import numpy as np

# Create two random 1000x1000 matrices using Python lists
matrix1_list = [[i + j for j in range(1000)] for i in range(1000)]
matrix2_list = [[i - j for j in range(1000)] for i in range(1000)]

# Measure time for matrix multiplication using Python Lists
start_time = time.time()
result_list = [[sum(matrix1_list[i][k] * matrix2_list[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
end_time = time.time()
print(f"Time taken for matrix multiplication using Python Lists: {end_time - start_time} seconds")

# Create two random 1000x1000 matrices using NumPy arrays
matrix1_array = np.random.rand(1000, 1000)
matrix2_array = np.random.rand(1000, 1000)

# Measure time for matrix multiplication using Numpy Arrays
start_time = time.time()
result_array = np.dot(matrix1_array, matrix2_array)
end_time = time.time()
print(f"Time taken for matrix multiplication using Numpy Arrays: {end_time - start_time} seconds")


Time taken for matrix multiplication using Python Lists: 195.26472997665405 seconds
Time taken for matrix multiplication using Numpy Arrays: 0.08686065673828125 seconds
